### ISSUE TITLE
Release .zip

### ISSUE THREAD

**Issue by renzenicolai** [schollii/pypubsub#1]
Hello,

I am running into issues with installing the "pypubsub" package on Arch Linux.
This package depends on the file "https://downloads.sf.net/project/$_project/$_project/$pkgver/$_pkgname-$pkgver.zip" which no longer exists because of your switch to Github.

Will you provide new releases as .zip files in the future and if so: where do I find those releases?

An alternative is a package that automatically builds your GIT repository: how stable will the master branch of this repository be?

Greetings,
Renze

**Comment by schollii** [comment]
Hi Renze, will it work if I release a .zip on pypi? Also is this for the latest only or do you need pypubsub 3.3? The latter is still supposed to be available on sf.net.
