### ISSUE TITLE
Include tests in archive

### ISSUE THREAD

**Issue by swt2c** [schollii/pypubsub#12]
This is a request to include the unit tests in the .zip release archives.  It is useful to be able to run the tests after building a package to make sure everything is working.

**Comment by schollii** [comment]
Makes sense for the .zip

**Comment by schollii** [comment]
Please use https://github.com/schollii/pypubsub/archive/v4.0.0.zip or https://github.com/schollii/pypubsub/archive/v3.3.0.zip for Pypubsub 3.3, both have the tests (these were fixed as a result of another ticket).
