### ISSUE TITLE
Tests are confusing and non-intuitive to run, requiring magic incantations.

### ISSUE THREAD

**Issue by eli-schwartz** [schollii/pypubsub#14]
- it depends on the current working directory that pytest is run from, because things like `open('test4_prov_module_actual.py', 'r')` and `self._parse_tree(_get_elem(open(xml, mode="r")` (where xml is **just** "xmlprovider_topics.xml"), instead of using `os.path.join(os.path.dirname(__file__), 'xmlprovider_topics.xml'`)
- src/pypubsub is not autodetected and added to the PYTHONPATH, whereas the common custom of using "modulename" as a directory in the root directory of the repository, would work fine.
- using tests/suite/ as the test directory, instead of just tests/, means pytest needs to be explicitly passed the test directory, instead of just detecting it automatically.

The ideal case would be that one could `git clone https://github.com/schollii/pypubsub && cd pypubsub && python -m pytest` and everything would just work without a fuss.
Currently it instead requires an additional `cd tests/suite && PYTHONPATH=$PWD../../src/ python -m pytest` for no discernable reason.

**Comment by schollii** [comment]
Apart from the title of the issue, excellent points ;)  Let's just agree that your use case would be easier to handle if the tests were setup differently. My recommendation is for you to fork, adjust to cover your use-case, submit PR. Don't forget to test with tox.

**Comment by schollii** [comment]
Since there hasn't been any motion on this, and the described limitations appear to be inconvenience rather than real blockers, I am going to close this. Feel free to re-open.
