### ISSUE TITLE
License file and release notes are confusing and non-intuitive to find.

### ISSUE THREAD

**Issue by eli-schwartz** [schollii/pypubsub#15]
Storing the license file as an oddly named file in src/pypubsub is very much not discoverable, and seems to be done for no reason other than to store it as package_data even though no one who was completely unable to discover either that or the release notes in the standard locations in the github web interface, is likely to go digging around in the egg directory.

On which note it looks like zip_safe=False may be being set just to make these files available outside of a zip, even though they're not relevant to the functionality of python at all. In fact, most people would just look at the setuptools metata via e.g. `pip show pypubsub`, and if they need the license for legal reasons they don't need it **in the egg distribution** so it would make more sense to have it in the root of the repository.

I've literally never seen it done this way before. :(

Also, moving it to the root of the repository and giving it a standard name means github can automatically detect and display the status in the header bar for the repo. :)

**Comment by schollii** [comment]
Excellent points, thanks for posting. I'd love to fix this immediately, but I don't have the opportunity to use Python much in my work (since almost a year!), let alone pypubsub (several years), so unless I can get someone to volunteer a PR, it will take some time to fix this. :(

**Comment by schollii** [comment]
I'm going to close this one as it is too broad in scope. Please open one issue per problem so each one is focussed and can be solved individually. Also it would be awesome if you could submit PRs for the different issues as I'm not entirely clear what solutions you are after (the solution for license is clear but not the others). Or perhaps we could fix over a chat on slack or such.
