### ISSUE TITLE
AUTO_TOPIC_OBJ implementation missing 

### ISSUE THREAD

**Issue by Dowwie** [schollii/pypubsub#2]
AUTO_TOPIC_OBJ is documented yet missing from the actual implementation?

**Comment by schollii** [comment]
Thank you for reporting this, I took a look and it was easy to fix (docs only). Should be visible tonight when I push update to github.

**Comment by Dowwie** [comment]
I actually wanted that functionality.  Hopefully you didn't just remove the documentation?

**Comment by schollii** [comment]
The functionality is there, just the docs have the wrong name: docs should mention `AUTO_TOPIC`. I would have preferred `AUTO_TOPIC_OBJ` but want to minimize chance of breaking existing apps.

**Comment by DevPlayer-** [comment]
I use it too.

**Comment by schollii** [comment]
The docs have been fixed as mentioned above.
