### ISSUE TITLE
Get the topic name, which "called" a listener

### ISSUE THREAD

**Issue by ReinhardDaemon** [schollii/pypubsub#23]
Hello,

I have this (not working) listener:
> def uhu_listener(payload):
>     print ("uhu_listener:")
>     print ("\t topic:    ", ??? GET TOPIC WHICH CALLED ME ???)
>     print("\t` payload: ", payload)

and this main entry:
> if __name__ == "__main__":
>    payload = 3
>    pub.subscribe(uhu_listener, topicName="uhu1")
>    pub.subscribe(uhu_listener, topicName="uhu2")
>    pub.subscribe(uhu_listener, topicName="uhu3")
>    pub.sendMessage("uhu2", payload=payload)

So, uhu_listener listens to 3 Topics (uhu1, uhu2 and uhu3).

Is there a way to determine the topic, which "called" the uhu_listener method?

BR,
Reinhard

**Comment by schollii** [comment]
On Wed., Nov. 21, 2018, 05:27 Reinhard Daemon, <notifications@github.com>
wrote:

> Hello,
>
> I have this (not working) listener:
>
> def uhu_listener(payload):
> print ("uhu_listener:")
> print ("\t topic: ", ??? GET TOPIC WHICH CALLED ME ???)
> print("\t` payload: ", payload)
>
> and this main entry:
>
> if *name* == "*main*":
> payload = 3
> pub.subscribe(uhu_listener, topicName="uhu1")
> pub.subscribe(uhu_listener, topicName="uhu2")
> pub.subscribe(uhu_listener, topicName="uhu3")
> pub.sendMessage("uhu2", payload=payload)
>
> So, uhu_listener listens to 3 Topics (uhu1, uhu2 and uhu3).
>
> Is there a way to determine the topic, which "called" the uhu_listener
> method?
>
> BR,
> Reinhard
>

Yes in the docs search for AUTO_TOPIC. It's discussed in a couple places,
such as
https://pypubsub.readthedocs.io/en/latest/usage/usage_basic_tasks.html?highlight=%22Topic%20as%20Message%20Data%22

**Comment by ReinhardDaemon** [comment]
Dear Schollii,

uhu_listener is registered to topics "uhu1", "uhu2" and "uhu3".

Please give me a complete example, how I have to change the signature of uhu_lilstener signature with AUTO_TOPIC to fulfill my requirements.

Thank you.

**Comment by schollii** [comment]
Please post what you have tried then I can show you how to fix. Note that in addition to that link in my previous reply, there are several examples if you search with Google, such as:

- https://pypubsub.readthedocs.io/en/v4.0.0/usage/usage_advanced_debug.html
- in the examples folder https://github.com/schollii/pypubsub/blob/master/examples/basic_kwargs/console_listeners.py.

**Comment by ReinhardDaemon** [comment]
Hello Schollii,

I played around and found this solution:



> from pubsub import pub
> 
> from pubsub.utils.notification import useNotifyByWriteFile
> useNotifyByWriteFile(prefix="DEBUG - PUBSUB:\r\n\t")
> 
> def uhu_listener(topic=pub.AUTO_TOPIC,payload=None):
>     print ("uhu_listener:")
>     print ("\ttopic:   ", topic.getName())
>     print ("\tpayload: ", payload)
>     pass
> 
> if __name__ == "__main__":
>    pub.subscribe(uhu_listener, topicName="uhu1")
>     pub.subscribe(uhu_listener, topicName="uhu2")
>    pub.sendMessage("uhu1", payload=111)            # --> uhu_listener
>     pub.sendMessage("uhu2", payload=222)            # --> uhu_listener
>     pub.sendMessage("uhu3", payload=333)            # --> to void


Am I doing it properly?

BR!

**Comment by schollii** [comment]
Looks good to me, does it print what you expect?

**Comment by ReinhardDaemon** [comment]
Dear Schollii,

yes, it works as expected.

I thought before that I have to use: 
   def uhu_listener(topic=pub.AUTO_TOPIC...
only in conjunction with:
   pub.subscribe(uhu_listener, pub.ALL_TOPICS)

Now I know better, thanks to your help.

I like the pub/sub concept a lot and already made one project that uses the cheap ESP8266 WiFi modules and a free of charger cloud broker (Flespi) to communicate over air, without IP addressing.
Project is at:
https://sourceforge.net/projects/esp8266-flespi-yum/

Now I see how easy and clear it is to use pub/sub within one python project in order to seperate 
the different tasks from one another and implementing a MVC pattern with it.

Thanks a lot for your great software lib!
Reinhard

**Comment by schollii** [comment]
@ReinhardDaemon That's fabulous to hear, thanks for the feedback! I hope you are using v4.0?

**Comment by schollii** [comment]
Seems like I can close this issue, please re-open if I misunderstood.
