### ISSUE TITLE
Conda-forge package

### ISSUE THREAD

**Issue by constantinpape** [schollii/pypubsub#24]
It would be very helpful to have this package on conda-forge https://conda-forge.org/
in order to have a reliable conda source for `pypubsub`.
So far, the package is only available on some third-party channel:
https://anaconda.org/ivoflipse/pypubsub

If someone with more knowledge of the package would support me, I could set up the conda-forge pull request.

**Comment by schollii** [comment]
I'm happy to help. I have no experience with Conda and limited time so IM
would likely be most effective. Slack? Hangouts? Other suggestion?

**Comment by yxdragon** [comment]
A question, is this package a sub model of wxpython? As I known, when I use pip install wxpython on windows or mac, the pubsub would be installed.

**Comment by constantinpape** [comment]
@schollii I don't think this will be very difficult, let's keep it here for now and switch to IM if any difficulties arise. For now, the only thing I would need to know is dependencies / requirements.
I had a look at the setup.py / I couldn't find a requirements.txt, so I guess there are no third-party dependencies?

@yxdragon pip has a system to install package requirements, so I guess it will install pubsub from pip as well.

**Comment by constantinpape** [comment]
I have made the conda-forge PR:
https://github.com/conda-forge/staged-recipes/pull/7531
@schollii please review

**Comment by schollii** [comment]
@constantinpape correct, no runtime dependencies. Test suite requires pytest and tox.

**Comment by constantinpape** [comment]
Ok, great!
Could you give an example on how to run the test suite?

Also, could you please confirm in the conda-forge PR if you want to be a maintainer?
Or let me know if you don't want to be a maintainer.
Being a maintainer means you have push rights to the package's feedstock (the actual recipe hosted by conda-forge), so you can update it e.g. with a new release.

**Comment by schollii** [comment]
Yes I would like to be a maintainer

**Comment by constantinpape** [comment]
Ok, please confirm this in the PR as well :).

**Comment by constantinpape** [comment]
The PR was merged and the package should be on conda-forge soon.
Thanks for the help @schollii.
