### ISSUE TITLE
deleting all topics

### ISSUE THREAD

**Issue by polymerchm** [schollii/pypubsub#3]
Need a simple way to remove all topics/subscribers/reset pubsub without stopping the interpreter.   Working in Pythonista which does not reset the interpreter when a script finishes.

**Comment by schollii** [comment]
Recently I added a clearTree() method on TopicManager. You would use it like this: 

``` python
from pubsub import pub
pub.getDefaultTopicMgr().clearTree() 
```

This will remove every topic and hence, every subscriber. I hope this helps!
