### ISSUE TITLE
Complete the new 3.4 branch release

### ISSUE THREAD

**Issue by schollii** [schollii/pypubsub#37]
The 3.4 version is needed because the 3.3 source was damaged during the transition from sourceforge to github a few years ago: the zip installer works and pubsub works, but installations based on the setup.py, including tests etc were not working properly because the zip was not designed to contain everything. 

Version 3.4 is being released to support python 2.7 *only*, and as such is a deprecated version! but being released so we have an official complete release that works in python 2.7. 

After the issues raised by TheChymera regarding version 3.3 of pypubsub, the only thing left to fix is the documentation such as READMEs, docs etc.

**Comment by schollii** [comment]
@TheChymera source release is at https://github.com/schollii/pypubsub/releases/tag/v3.4.0rc1 and the wheel is at https://pypi.org/project/PyPubSub/3.4.1rc1/

**Comment by schollii** [comment]
@thechymera please use the latest 3.4.2. This closes the ticket unless you spot an issue when you try to use it.

**Comment by TheChymera** [comment]
Thank you :)
