### ISSUE TITLE
Feature request: subscribe non-global callables

### ISSUE THREAD

**Issue by DevPlayer-** [schollii/pypubsub#4]
Seems I am only able to pub.subscribe(some_callable_in_global_namespace, 'topic'). If that is so can we change that to allow for non-globals to subscribe.

My current work-around is something like this:

```
def init(kwargs={}):
    global start, inited
    inited = True
    def start(kwargs={}):
        global pause, started
        started = True
        def pause(kwargs={}):
            global paused
            paused = True
            # do stuff
        pub.subscribe(pause,'pause.myaddonA')
    pub.subscribe(start, 'start.myaddonA')
pub.subscribe(init, 'init.myaddonA')
```

**Comment by schollii** [comment]
Listeners don't have to be global, they can be data members. So another way would be to define an attribute on the enclosing function:

``` python
def init(kwargs={}):
    def start(kwargs={}):
        init.state = 'started'
        ...
    pub.subscribe(start, 'start.myaddonA')
    init.start = start  # strong ref will live as long as init
    init.state = 'inited'

pub.subscribe(init, 'init.myaddonA')
init.state = None
```

**Comment by DevPlayer-** [comment]
After some digging I think I see my misunderstanding of the API and pubsub's expected behavior. I presume this is related to the design decision for pubsub to send messages only to callables with strong references and ignore callables with weak references, therefore allowing decoupling of concerns. What threw me was no exceptions where raised when subscribing a weak referenced callable. If this is close to being accurate please let me know here and we'll close this feature request.

**Comment by schollii** [comment]
You are bang on. See http://pypubsub.readthedocs.io/en/latest/usage/usage_basic_tasks.html?highlight=Weak#id4 for a  short discussion and please let me know if there is anything we could add to make this trap better documented. 

Unfortunetely I can't think of a good way of guarding against dead listener because at the time of subscription there is at least one strong ref to the callable, and the lifetime of this strong ref(s) depends on details above the call stack. If you think of something let me know.

**Comment by DevPlayer-** [comment]
I do not know if there is a good way to guard against dead listeners while decoupling concerns. However perhaps if pub.subscribe() had a optional third argument being a callback when a callable object's strong reference count equals 1 (basicaly zero). Or if optionally enabled during instantation of a publisher (i.e. pubsub.pub) issue a sendMessage('special topic", callable_going_weak). Also there is the Python Warning system instead of exceptions one could trap on during pub.subscribe().

Just something to think about.

**Comment by schollii** [comment]
DevPlayer, there is no way to guard against dead listeners that isn't easy to thwart. The reference could easily be more than 1 at subscription time and still lead to a dead listener shortly after. Or the reference count could be just 1 and if the listener is returned it will not die, so count=1 is just not reliable. 

However, look at the testDeadListener() test in the test suite: it gives an example of using the notification system that pypubsub supports to track various events in the pubsub engine (dead listeners is one of several). If you only turn on notification for dead listeners, and you use logging, this will give you an easy way to assess whether any listener is dying prematurely. 

P.s. don't forget to reopen the issue if you comment, else I don't see it as open in github (luckily I get an email but just in case).
