### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by wossx** [schollii/pypubsub#5]
```
def foo():
    pass

import wx.lib.plot
from pubsub import pub
pub.subscribe(foo, 'topic')
```

Result of my reduced code in Python 3.6:

_D:\Python36\lib\site-packages\pubsub\core\callables.py:147: DeprecationWarning:
inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  (allParams, varParamName, varOptParamName, defaultVals) = getargspec(func)_

(not without wx.lib.plot, and only in Python 3)

**Comment by schollii** [comment]
Gee I don't know what happened as I know I checked a few times for issues, sorry about the delay. I will look into this.

**Comment by wossx** [comment]
I use these modifications:

--- R:/callables_orig.py    H márc. 12 14:55:20 2018
+++ R:/callables.py H márc. 12 14:55:27 2018
@@ -15 +15 @@ CallArgsInfo regarding its autoTopicArgName data m
-from inspect import getargspec, ismethod, isfunction
+from inspect import getfullargspec, ismethod, isfunction
@@ -147 +147 @@ class CallArgsInfo:
-(allParams, varParamName, varOptParamName, defaultVals) = getargspec(func)
+(allParams, varParamName, varOptParamName, defaultVals, *foo) = getfullargspec(func)

**Comment by schollii** [comment]
Thanks! I'm on the hills this week but I should be able to run this through the test suite next week.

**Comment by schollii** [comment]
@wossx Any chance you could submit a PR?

**Comment by schollii** [comment]
This was fixed in another ticket.
