### ISSUE TITLE
Using wx.lib.pubsub with PyInstaller

### ISSUE THREAD

**Issue by david-hughes** [schollii/pypubsub#7]
wxPython 4 (Phoenix) has now been officially released and supports Python 3. Py2exe has not been fully converted for Python 3 and is now no longer maintained. Neither is Esky the software updater package that is (was) callable from wxPython. The way forward seems to be via PyInstaller and PyUpdater. Unfortunately when attempting to use PyInstaller on a wxPython application that uses pubsub it fails to import the items that are in wx\lib\pubsub\core\kwargs.

Looking further into PyInstaller I see it has a powerful mechanism for locating problematic imports via Python scripted "Hooks" and that many such have been published at https://github.com/pyinstaller/pyinstaller for various Python packages. There is one there for wx.lib.pubsub but looking at the open Issues there have been several, so far unsuccessful attempts to complete it going back several years, in particular, issues #1367, #1530, #2215 and #2233.

Is there any recommendation as to how pubsub can be used by PyInstaller?

David Hughes
Forestfield Software

**Comment by schollii** [comment]
Hi David, the latest version of pypubsub likely solves this. Unfortunately I have not had time to integrate it to wxpython (not a big task but been extremely busy). Can you try with a standalone install of pypubsub and replace occurrences of wx.lib.pubsub in your code, should be easy via search/replace.

**Comment by david-hughes** [comment]
Pypubsub (4.0.0) installed and working fine with PyInstaller, thanks.

Is there anything I can do to help update wx.lib.pubsub? I'm familiar with raising pull requests for wxPython.

**Comment by schollii** [comment]
Gosh that would be *so* awesome if you could look after that. I have not
had an opportunity to use wxpython for a while so mods/fixes are 100%
driven by community. 

That's awesome news about pyinstaller, it was one of the reasons for the
changes made in 4.0. It would be good to update the docs and perhaps post
in a couple of places where help was asked about this issue. But I have no
experience using pyinstaller, what info should be added to the docs, and
where to post? Let me know how I can help sort this out.

**Comment by david-hughes** [comment]
I have raised a pull request for wxPython - https://github.com/wxWidgets/Phoenix/pull/782

If and when it gets released there are a couple of places in github/pyinstaller where I can report that things have been fixed. But as the original issues appear to have been raised wrt wx.lib.pubsub rather than Pypubsub, it's probably best to wait until then.

The documentation at http://pypubsub.readthedocs.io/en/stable/development/py2exe.html maybe needs updating with a deprecation warning about py2exe and a reference to PyInstaller. I didn't need any special flags or settings for it to freeze pubsub and created my frozen app directly from the command line - *pyinstaller MyMain.py*

**Comment by schollii** [comment]
How about we remove what's in dev_index.rst, and add a section in docs/usage/howtos/index.rst for packaging? Would the gist of it be that py2exe and cx-freeze are not supported but that pyinstaller is? Do you have an example pyinstaller configuration to contribute, maybe with a main.py that imports wx.lib.pubsub? These two files would go would go in the examples folder and get referenced in the .RST file.

**Comment by david-hughes** [comment]
The re-organisation sounds good. I think it needs to be impartial regarding which packager to use. Pehaps say some are platform-specific like p2exe for Windows and py2app for MacOS - although it would be fair to add that py2exe is Python 2 only and is not currently being maintained. I believe py2app is active but I haven't personally used it with Python 3. Others like cx-freeze and pyinstaller are cross-platform, although the build for a specific OS needs to be done under that OS - possibly in a virtual machine running in a different OS. Both cx-freeze and pyinstaller are currently active and being maintained. All of the above are available through PyPI and pip.

The documentation for pyinstaller is at https://pyinstaller.readthedocs.io/en/latest/ and the first time you run it for ``main.py`` it creates a setup file called ``main.spec`` and if anything non-standard is required or there are hidden imports to be found, the .spec file can be modified and future builds run against that instead of the .py file. Since installing pubsub 4 it hasn't been necessary to run anything but ``pyinstaller main.py`` but I can provide an example if you think it would help.

**Comment by schollii** [comment]
Strangely, I just saw your reply today. Thanks a lot for the PR and merging, much appreciated. Unfortunately my work does not involve Python let alone pypubsub so it's difficult to find the time to do this sort of stuff. I noticed there were a couple of patches on the pypubsub 3.3 that I put in wxPython a couple of years ago, any chance of copying those into standalone pypubsub v4?

**Comment by schollii** [comment]
@david-hughes any chance you could create a separate issue for the docs stuff? Honestly I don't have time to learn PyInstaller so the only way this will get fixed is if someone who uses it submits a PR for edits to the docs. So I'm going to close this as the original problem seems fixed.
